/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbpButton: typeof import('@lsw-abpvue/theme-shared')['AbpButton']
    AbpConfirmHost: typeof import('@lsw-abpvue/theme-shared')['AbpConfirmHost']
    AbpDataTable: typeof import('@lsw-abpvue/components')['AbpDataTable']
    AbpDatePicker: typeof import('@lsw-abpvue/theme-shared')['AbpDatePicker']
    AbpDynamicLayout: typeof import('@lsw-abpvue/core/router')['AbpDynamicLayout']
    AbpExtensibleForm: typeof import('@lsw-abpvue/components')['AbpExtensibleForm']
    AbpExtensibleTable: typeof import('@lsw-abpvue/components')['AbpExtensibleTable']
    AbpFormField: typeof import('@lsw-abpvue/theme-shared')['AbpFormField']
    AbpGridActions: typeof import('@lsw-abpvue/components')['AbpGridActions']
    AbpInput: typeof import('@lsw-abpvue/theme-shared')['AbpInput']
    AbpModal: typeof import('@lsw-abpvue/theme-shared')['AbpModal']
    AbpPage: typeof import('@lsw-abpvue/components')['AbpPage']
    AbpPageToolbar: typeof import('@lsw-abpvue/components')['AbpPageToolbar']
    AbpPagination: typeof import('@lsw-abpvue/theme-shared')['AbpPagination']
    AbpPermission: typeof import('@lsw-abpvue/core')['AbpPermission']
    AbpRecordModal: typeof import('@lsw-abpvue/components')['AbpRecordModal']
    AbpReplaceable: typeof import('@lsw-abpvue/core')['AbpReplaceable']
    AbpRouterOutlet: typeof import('@lsw-abpvue/core/router')['AbpRouterOutlet']
    AbpSelect: typeof import('@lsw-abpvue/theme-shared')['AbpSelect']
    AbpSpinner: typeof import('@lsw-abpvue/theme-shared')['AbpSpinner']
    AbpTabList: typeof import('@lsw-abpvue/components')['AbpTabList']
    AbpToastHost: typeof import('@lsw-abpvue/theme-shared')['AbpToastHost']
    AbpToggle: typeof import('@lsw-abpvue/theme-shared')['AbpToggle']
    AbpTypeahead: typeof import('@lsw-abpvue/theme-shared')['AbpTypeahead']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
