<!-- Generated by `abpv generate`. The columns, the form fields and the buttons are in
     the extensions file next door, which is where to change what this page shows. -->

<script setup lang="ts">
import {
  AbpExtensibleTable,
  AbpPage,
  AbpPageToolbar,
  AbpRecordModal,
  useRecordEditor,
} from '@lsw-abpvue/components';
import { inject as injectAbp, useListService } from '@lsw-abpvue/core';
import { BookService } from '../proxy/book-store/books';
import type { BookDto, CreateUpdateBookDto } from '../proxy/book-store/books';
import { BOOKS, BOOKS_PAGE, registerBooksExtensions } from './books.extensions';

const bookService = injectAbp(BookService);

const list = useListService({ persistKey: BOOKS });
const { items } = list.hookToQuery(query => bookService.getList(query));

registerBooksExtensions();

const editor = useRecordEditor<BookDto>({
  identifier: BOOKS,
  reload: () => list.get(),
  create: body => bookService.create(body as unknown as CreateUpdateBookDto),
  update: (id, body) => bookService.update(id, body as unknown as CreateUpdateBookDto),
  delete: id => bookService.delete(id),
  idOf: record => record.id,
  nameOf: record => String(record.name ?? ''),
  deletionMessage: 'BookStore::BookDeletionConfirmationMessage',
  providers: [
    {
      provide: BOOKS_PAGE,
      useValue: {
        add: () => editor.show(),
        edit: async (record: BookDto) => editor.show(await bookService.get(record.id ?? '')),
        remove: (record: BookDto) => editor.remove(record),
      },
    },
  ],
});
</script>

<template>
  <AbpPage title="BookStore::Menu:Books">
    <template #toolbar>
      <AbpPageToolbar :data="items" />
    </template>

    <AbpExtensibleTable
      :data="items"
      :list="list"
      record-key="id"
      caption="BookStore::Menu:Books"
      searchable
    />

    <AbpRecordModal
      :editor="editor"
      label="BookStore::Menu:Books"
      create-title="BookStore::NewBook"
    />
  </AbpPage>
</template>
