<!-- Generated by `abpv generate`. The columns, the form fields and the buttons are in
     the extensions file next door, which is where to change what this page shows. -->

<script setup lang="ts">
import {
  AbpExtensibleTable,
  AbpPage,
  AbpPageToolbar,
  AbpRecordModal,
  useRecordEditor,
} from '@lsw-abpvue/components';
import { inject as injectAbp, useListService } from '@lsw-abpvue/core';
import { IdentityRoleService } from '../proxy/volo/abp/identity';
import type {
  IdentityRoleCreateDto,
  IdentityRoleDto,
  IdentityRoleUpdateDto,
} from '../proxy/volo/abp/identity';
import {
  IDENTITY_ROLES,
  IDENTITY_ROLES_PAGE,
  registerIdentityRolesExtensions,
} from './identity-roles.extensions';

const identityRoleService = injectAbp(IdentityRoleService);

const list = useListService({ persistKey: IDENTITY_ROLES });
const { items } = list.hookToQuery(query => identityRoleService.getList(query));

registerIdentityRolesExtensions();

const editor = useRecordEditor<IdentityRoleDto>({
  identifier: IDENTITY_ROLES,
  reload: () => list.get(),
  create: body => identityRoleService.create(body as unknown as IdentityRoleCreateDto),
  update: (id, body) => identityRoleService.update(id, body as unknown as IdentityRoleUpdateDto),
  delete: id => identityRoleService.delete(id),
  idOf: record => record.id,
  stampOf: record => record.concurrencyStamp,
  nameOf: record => String(record.name ?? ''),
  deletionMessage: 'BookStore::IdentityRoleDeletionConfirmationMessage',
  providers: [
    {
      provide: IDENTITY_ROLES_PAGE,
      useValue: {
        add: () => editor.show(),
        edit: async (record: IdentityRoleDto) =>
          editor.show(await identityRoleService.get(record.id ?? '')),
        remove: (record: IdentityRoleDto) => editor.remove(record),
      },
    },
  ],
});
</script>

<template>
  <AbpPage title="Generated roles">
    <template #toolbar>
      <AbpPageToolbar :data="items" />
    </template>

    <AbpExtensibleTable :data="items" :list="list" record-key="id" caption="Generated roles" />

    <AbpRecordModal
      :editor="editor"
      label="Generated roles"
      create-title="BookStore::NewIdentityRole"
    />
  </AbpPage>
</template>
