import { ImportCollector } from '../generator/imports.js';
import { camelCase } from '../generator/names.js';
import { namesOf } from './emit-extensions.js';
import type { EntityPage } from './entity.js';

const COMPONENTS = '@lsw-abpvue/components';
const CORE = '@lsw-abpvue/core';

const HEADER = [
  '<!-- Generated by `abpv generate`. The columns, the form fields and the buttons are in',
  '     the extensions file next door, which is where to change what this page shows. -->',
].join('\n');

/**
 * The `<Entity>Page.vue` of a generated page: a list, a dialog and the four requests
 * behind them. Everything else -- pagination, sorting, validation, the permission
 * checks on the buttons -- is the extension system's.
 *
 * @param page What was read off the API definition
 */
export function emitPage(page: EntityPage): string {
  const names = namesOf(page);
  const record = page.types.record;
  const service = camelCase(page.service.name);
  const imports = new ImportCollector();

  for (const name of [
    'AbpExtensibleTable',
    'AbpPage',
    'AbpPageToolbar',
    'AbpRecordModal',
    'useRecordEditor',
  ]) {
    imports.addValue(COMPONENTS, name);
  }

  imports.addValue(CORE, 'inject as injectAbp');
  imports.addValue(CORE, 'useListService');
  const proxy = `../proxy/${page.service.directory}`;

  imports.addValue(proxy, page.service.name);
  for (const type of new Set([record, page.types.create, page.types.update])) {
    imports.addType(proxy, type);
  }
  imports.addValue(`./${page.fileBase}.extensions`, names.key);
  imports.addValue(`./${page.fileBase}.extensions`, names.token);
  imports.addValue(`./${page.fileBase}.extensions`, names.register);

  const create = page.types.create;
  const update = page.types.update;

  const editor = [
    `const editor = useRecordEditor<${record}>({`,
    `  identifier: ${names.key},`,
    '  reload: () => list.get(),',
    // The fields come from the extension system, so the body's shape is only known at
    // runtime. The cast is what says the server is the one that checks it.
    `  create: body => ${service}.create(body as unknown as ${create}),`,
    `  update: (id, body) => ${service}.update(id, body as unknown as ${update}),`,
    `  delete: id => ${service}.delete(id),`,
    `  idOf: record => record.id,`,
    ...(page.concurrencyStamp ? ['  stampOf: record => record.concurrencyStamp,'] : []),
    page.nameProperty
      ? `  nameOf: record => String(record.${page.nameProperty} ?? ''),`
      : "  nameOf: () => '',",
    `  deletionMessage: '${page.resource}::${page.entity}DeletionConfirmationMessage',`,
    '  providers: [',
    '    {',
    `      provide: ${names.token},`,
    '      useValue: {',
    '        add: () => editor.show(),',
    ...(page.reload
      ? [
          `        edit: async (record: ${record}) => editor.show(await ${service}.get(record.id ?? '')),`,
        ]
      : [`        edit: (record: ${record}) => editor.show(record),`]),
    `        remove: (record: ${record}) => editor.remove(record),`,
    '      },',
    '    },',
    '  ],',
    '});',
  ];

  const script = [
    '<script setup lang="ts">',
    imports.render(),
    '',
    `const ${service} = injectAbp(${page.service.name});`,
    '',
    `const list = useListService({ persistKey: ${names.key} });`,
    `const { items } = list.hookToQuery(query => ${service}.getList(query));`,
    '',
    `${names.register}();`,
    '',
    ...editor,
    '</script>',
  ];

  const template = [
    '<template>',
    `  <AbpPage title="${page.menuKey}">`,
    '    <template #toolbar>',
    '      <AbpPageToolbar :data="items" />',
    '    </template>',
    '',
    '    <AbpExtensibleTable',
    '      :data="items"',
    '      :list="list"',
    '      record-key="id"',
    `      caption="${page.menuKey}"`,
    ...(page.filter ? ['      searchable'] : []),
    '    />',
    '',
    '    <AbpRecordModal',
    '      :editor="editor"',
    `      label="${page.menuKey}"`,
    `      create-title="${page.resource}::New${page.entity}"`,
    '    />',
    '  </AbpPage>',
    '</template>',
  ];

  return `${HEADER}\n\n${script.join('\n')}\n\n${template.join('\n')}\n`;
}
