import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const fixture = join(repoRoot, 'e2e/fixtures/application-localization.en.json');

interface Resource {
  texts?: Record<string, string>;
  baseResources?: string[];
}

const resources: Record<string, Resource> = existsSync(fixture)
  ? ((JSON.parse(readFileSync(fixture, 'utf8')) as { resources?: Record<string, Resource> })
      .resources ?? {})
  : {};

/** A resource inherits from the ones it names, the way the localizer resolves them. */
function textsOf(name: string, seen = new Set<string>()): Record<string, string> {
  const resource = resources[name];
  if (!resource || seen.has(name)) return {};
  seen.add(name);

  const inherited = (resource.baseResources ?? []).map(base => textsOf(base, seen));
  return Object.assign({}, ...inherited, resource.texts) as Record<string, string>;
}

function* sources(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* sources(path);
    else if (/\.(ts|vue)$/.test(entry.name) && !/\.(spec|test-d)\.ts$/.test(entry.name)) yield path;
  }
}

interface Usage {
  resource: string;
  key: string;
  file: string;
  hasDefault: boolean;
}

/** `{ key: 'AbpUi::Menu', defaultValue: 'Menu' }` -- the escape hatch, and the proof of it. */
const WITH_DEFAULT = /key:\s*['"]([^'"]+)['"]\s*,\s*defaultValue:/g;
// Only inside a string literal, and never inside a comment: prose says `Resource::Key`
// too, and a doc comment naming the shape is not a usage of it.
const ANY_KEY = /['"]([A-Za-z][A-Za-z0-9]*)::([^'"\s]+)['"]/g;
const COMMENTS = /\/\*[\s\S]*?\*\/|(?:^|\s)\/\/[^\n]*/g;

function usagesIn(file: string): Usage[] {
  const body = readFileSync(file, 'utf8').replace(COMMENTS, ' ');
  const defaulted = new Set([...body.matchAll(WITH_DEFAULT)].map(match => match[1]));

  return [...body.matchAll(ANY_KEY)].map(match => ({
    resource: match[1] as string,
    key: match[2] as string,
    file: relative(repoRoot, file),
    hasDefault: defaulted.has(`${match[1]}::${match[2]}`),
  }));
}

/**
 * Every package's `src`, and every secondary entry point's (`config/src`, `router/src`).
 * A module's `/config` ships text too -- the setting management tabs live there -- and
 * leaving it out was a whole entry point outside the gate.
 */
function sourceRoots(): string[] {
  const roots: string[] = [];

  for (const entry of readdirSync(join(repoRoot, 'packages'), { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const packageRoot = join(repoRoot, 'packages', entry.name);
    roots.push(join(packageRoot, 'src'));

    for (const inner of readdirSync(packageRoot, { withFileTypes: true })) {
      // Generated proxies say what the backend says, keys included.
      if (!inner.isDirectory() || inner.name === 'proxy' || inner.name === 'src') continue;
      roots.push(join(packageRoot, inner.name, 'src'));
    }
  }

  return roots.filter(existsSync);
}

const packages = sourceRoots();

const usages = packages.flatMap(dir => [...sources(dir)].flatMap(usagesIn));

/**
 * Every `Resource::Key` a package ships has to be one the backend can actually resolve.
 * A key that is not resolves to its own name, which is how a button ends up labelled
 * `LoadingWithThreeDot`. Where ABP genuinely has no key for something, the usage carries
 * a `defaultValue` and says so out loud.
 */
describe('the localization keys the packages ship', () => {
  it('has fixtures to check against', () => {
    // Regenerated by `scripts/capture-fixtures.sh` against a live backend.
    expect(Object.keys(resources).length).toBeGreaterThan(0);
  });

  it('finds keys to check', () => {
    expect(usages.length).toBeGreaterThan(0);
  });

  it('either resolves against the backend or carries a default', () => {
    const unresolved = usages
      .filter(usage => !(usage.key in textsOf(usage.resource)) && !usage.hasDefault)
      .map(usage => `${usage.resource}::${usage.key} (${usage.file})`);

    expect([...new Set(unresolved)]).toEqual([]);
  });
});
